name: Continuous Integration

on: [push, pull_request, fork]

jobs:

  build:

    runs-on: macos-latest

    steps:
      - name: Checkout untangling-tools-benchmark
        uses: actions/checkout@v3
        with: 
          repository: Thomsch/untangling-tools-benchmark
          ref: ci                              # ci branch has end to end tests; not yet merged to main
          path: untangling-tools-benchmark     # Relative path under $GITHUB_WORKSPACE to place the repository
      - name: Install Python 3.8.15
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # - run: echo "JAVA11_HOME=$JAVA_HOME" >> $GITHUB_ENV
      - name: Install Java 8 as default
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Install Flexeme
        uses: actions/checkout@v3
        with: 
          repository: Thomsch/Flexeme
          path: Flexeme
      # - name: ls ${HOME}
      #   run: |
      #     echo HOME=${HOME}
      #     ls -al ${HOME}
      #     find ${HOME}
      - name: Install Flexeme dependencies
        run: |
          brew install graphviz
          pip install pygraphviz
          pip install -e ${GITHUB_WORKSPACE}/Flexeme
      - run: cd ${GITHUB_WORKSPACE}/untangling-tools-benchmark
      - name: Install Python modules and MacOS dependencies
        run: |
          pip install -U -r ${GITHUB_WORKSPACE}/untangling-tools-benchmark/requirements.txt
          brew install cpanminus
          brew install wget
          brew install coreutils
      - name: Install Defects4J
        uses: actions/checkout@v3
        with: 
          repository: rjust/defects4j
          path: defects4j
      - name: Initialize Defects4J
        run: |
          d4j="${GITHUB_WORKSPACE}/defects4j"
          cd $d4j
          cpanm --installdeps .
          ./init.sh
      - name: List working directory paths
        run: |
          benchmark="${GITHUB_WORKSPACE}/untangling-tools-benchmark"
          echo $benchmark
          ls -al ${GITHUB_WORKSPACE}
      - name: Add Defects4J's executable to PATH
        run: |
          D4J_EXEC="${d4j}/framework/bin"
          export PATH="${D4J_EXEC}:$PATH"
      - name: Fill in environment variables
        run: |
          echo "DEFECTS4J_HOME=${d4j}" >> $GITHUB_ENV
          echo "JAVA_11=${JAVA11_HOME}/bin/java" >> $GITHUB_ENV
      - name: Check installations and dependencies
        run: |
          ${GITHUB_WORKSPACE}/untangling-tools-benchmark/test/check_installation.sh
      - name: run end-to-end tests
        run: |
          export PYTHONHASHSEED=0
          ${GITHUB_WORKSPACE}/untangling-tools-benchmark/test/e2e.sh


  # [ -f "${benchmark}/.env-template" ] || (pwd && ls -al && false)
  # echo "DEFECTS4J_HOME=${d4j}" > "${benchmark}/.env"
  # echo "JAVA_11=${JAVA11_HOME}/bin/java" >> "${benchmark}/.env"