name: Continuous Integration

on: [push, pull_request, fork]

jobs:

  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: echo "JAVA11_HOME=$JAVA_HOME" >> $GITHUB_ENV
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: |
          git config --global user.name "VirtualMachine"
          git config --global user.email "vm@nowhere.nowhere"
      - name: clone Flexeme
        run: |
          git clone https://github.com/Thomsch/Flexeme.git ${HOME}/Flexeme
      - name: set
        run: set | sort
      - name: ls GITHUB_WORKSPACE
        run: |
          echo GITHUB_WORKSPACE=${GITHUB_WORKSPACE}
          ls -al ${GITHUB_WORKSPACE}
      - name: ls ${HOME}
        run: |
          echo HOME=${HOME}
          ls -al ${HOME}
          find ${HOME}
      - name: install Flexeme dependencies
        run: |
          brew install graphviz
          pip install pygraphviz
          pip install -e ${HOME}/Flexeme
      - run: cd ${HOME}/untangling-tools-benchmark
      - name: install Python modules and MacOS dependencies
        run: |
          pip install -U -r requirements.txt
          brew install cpanminus
          brew install wget
          brew install coreutils
      - name: clone Defects4J
        run: |
          git clone https://github.com/rjust/defects4j ${HOME}/defects4j
      - name: install Defects4J
        run: |
          cd ${HOME}/defects4j
          cpanm --installdeps .
          ./init.sh
      - name: set up environment variables
        run: |
          D4J_EXEC="$current_path/framework/bin"
          export PATH="$D4J_EXEC:$PATH"
          echo "DEFECTS4J_HOME=$current_path" > .env
          echo "JAVA_11=$JAVA11_HOME/bin/java" >> .env
      - name: check installations and dependencies
        run: ./test/check_installation.sh
      - name: run end-to-end tests
        run: |
          export PYTHONHASHSEED=0
          ./test/e2e.sh
