name: End-to-end test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mdernst/untangling-ubuntu

    steps:
      - uses: actions/checkout@v3

## TODO: Does this need the following?
#         python3 -m venv .venv
#         source .venv/bin/activate
      - name: Python requirements
        run: |
          pip install -U -r requirements.txt

      - name: Install Flexeme
        run: |
          git clone https://github.com/Thomsch/Flexeme ../Flexeme
          pip install -e ../Flexeme

      - name: .env file
        run:
          echo "DEFECTS4J_HOME=\"${DEFECTS4J_HOME}\"" > .env
          echo "JAVA11_HOME=\"${JAVA11_HOME}\"" >> .env

      - name: e2e.sh
        run: src/python/test/e2e.sh
