name: make check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install Python modules
        run: pip install -U -r requirements.txt
      - name: apt-get update
        run: sudo apt-get update
      - name: Install shellcheck and checkbashisms
        run: sudo apt install -y shellcheck devscripts || (sleep 60 && sudo apt install -y shellcheck devscripts)
      - name: Install bats
        run: sudo apt install -y bats
      - name: make check
        run: make check
