name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install Python modules
        run: pip install -U -r requirements.txt
      - name: install checkbashisms
        run: sudo apt-get -y install devscripts

      - name: make check
        run: make check
