name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install Python modules
        run: python3 -m pip install --upgrade black flake8 pylint

      - name: make check
        run: |
          make check
